//! In-app update wiring — docs/UPDATES.md §3.
//!
//! The heavy lifting is done by `tauri-plugin-updater`, driven from the
//! webview (see `src/updates.tsx`). This module owns the one thing the plugin
//! cannot do for us: deciding whether updates are *configured at all*.
//!
//! Why that matters. The updater refuses any payload whose minisign signature
//! does not verify against the public key baked into `tauri.conf.json`, and
//! that key is generated by the maintainer — it cannot live in the repo before
//! the first release (docs/RELEASING.md §2). Two failure modes follow, and
//! both used to be fatal or cryptic:
//!
//! * `plugins.updater` missing entirely → the plugin's own `initialize` fails
//!   to deserialize its config, `Builder::build()` returns `Err`, and Sendro
//!   panics *at startup*. An app that will not open because updates are not
//!   set up is not acceptable.
//! * `plugins.updater.pubkey` still the placeholder → the app starts, offers
//!   "Update now", downloads the installer and then dies on a minisign error
//!   the user cannot act on.
//!
//! So the config is inspected before the Tauri builder runs: the updater and
//! process plugins are only registered when the key looks real, and the UI
//! asks `updater_status` and says "Updates are not configured" otherwise.

use serde::Serialize;
use tauri::Config;

/// The literal that ships in `tauri.conf.json`. The maintainer replaces it
/// with the output of `npm run tauri signer generate` — see docs/RELEASING.md.
pub const PUBKEY_PLACEHOLDER: &str = "REPLACE_WITH_UPDATER_PUBLIC_KEY";

/// What the webview needs to know before it offers anything update-shaped.
#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct UpdaterStatus {
    /// True when the plugin was registered and `check()` can be called.
    pub configured: bool,
    /// Plain-language reason, when it was not. `None` when configured.
    pub reason: Option<String>,
    /// The manifest URLs this build would poll, for the Settings screen.
    pub endpoints: Vec<String>,
}

/// Read `plugins.updater` out of the compiled-in config and judge it.
///
/// Deliberately tolerant: it never panics and never returns `Err`, because a
/// broken updater config must degrade to "updates are off", not to a crash.
pub fn inspect(config: &Config) -> UpdaterStatus {
    let Some(raw) = config.plugins.0.get("updater") else {
        return UpdaterStatus {
            configured: false,
            reason: Some(
                "This build has no updater configuration (plugins.updater is missing from \
                 tauri.conf.json)."
                    .to_string(),
            ),
            endpoints: Vec::new(),
        };
    };

    let endpoints: Vec<String> = raw
        .get("endpoints")
        .and_then(|value| value.as_array())
        .map(|list| {
            list.iter()
                .filter_map(|value| value.as_str().map(str::to_string))
                .collect()
        })
        .unwrap_or_default();

    let pubkey = raw
        .get("pubkey")
        .and_then(|value| value.as_str())
        .unwrap_or_default()
        .trim();

    let reason = if pubkey.is_empty() || pubkey == PUBKEY_PLACEHOLDER {
        Some(
            "This build was made without an update signing key, so it cannot verify a \
             download. Install new versions from the release page instead."
                .to_string(),
        )
    } else if endpoints.is_empty() {
        Some("This build has no update endpoint configured.".to_string())
    } else if !endpoints.iter().all(|url| url.starts_with("https://")) {
        Some("The update endpoint must use https.".to_string())
    } else {
        None
    };

    UpdaterStatus {
        configured: reason.is_none(),
        reason,
        endpoints,
    }
}

/// Managed by `run()` whether or not the plugin was registered, so the webview
/// always gets an answer instead of an "unknown command" rejection.
#[tauri::command]
pub fn updater_status(status: tauri::State<'_, UpdaterStatus>) -> UpdaterStatus {
    status.inner().clone()
}
